server:
  port: 8761                    # 指定该Eureka实例的端口
 
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${eurekaip:http://127.0.0.1:8761/eureka/}
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    
