server:
  port: 8761 
spring:
  application:
    name: happyplay-eureka
   
                    # 指定该Eureka实例的端口
 
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${toEurekaIp:http://127.0.0.1:8761/eureka/}
  instance:
    preferIpAddress: true
    instance-id: ${localIp:127.0.0.1:8761/eureka}
    
