server:
  port: 8040
  
spring:
  application:
    name: happyplay-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/war3shenzuo/spring-cloud-happyplay/
          search-paths: config-repo
          username: null
          password: null
eureka:
  client:
    serviceUrl:
      defaultZone: http://118.89.185.176:8761/eureka/,http://182.254.232.158:8761/eureka/
  instance:
    preferIpAddress: true